// Short, plain-English definitions for the less-obvious stats, surfaced as hover
// tooltips. Keyed by the exact label shown in the UI so components can auto-look-up.
export const GLOSSARY: Record<string, string> = {
  // skater scoring / shooting
  "G": "Goals.",
  "A": "Assists.",
  "P": "Points — goals + assists.",
  "PTS": "Points — goals + assists.",
  "+/−": "Plus/minus — even-strength goal differential while this player is on the ice.",
  "S": "Shots on goal.",
  "S%": "Shooting % — goals per shot on goal.",
  "ixG": "Individual expected goals — the sum of this player's shot probabilities; how many an average shooter scores on those chances.",
  "xG/60": "Expected goals per 60 minutes — chance-creation rate, pace-adjusted.",
  "HD chances": "High-danger chances — shots from the slot / home-plate area, where most goals come from.",
  "CF%": "Corsi-for % — share of shot attempts (on goal + missed + blocked) while on the ice. A possession proxy.",
  "IPP": "Individual point % — share of the team's on-ice goals this player got a point on.",
  "xGF / xGA": "On-ice expected goals for / against — chance quality created vs. allowed while on the ice.",
  // skating (CV)
  "Top speed": "Top skating speed reached (mph) — from CV tracking.",
  "Avg speed": "Average skating speed (mph) — from CV tracking.",
  "Distance": "Distance skated (miles) — from CV tracking.",
  "Distance (season)": "Total distance skated over the season (miles) — from CV tracking.",
  // box-score columns
  "SM": "Shots that missed the net.",
  "BS": "Blocked shots — shots this player blocked.",
  "PN": "Penalties taken.",
  "PIM": "Penalty minutes.",
  "HT": "Hits delivered.",
  "TK": "Takeaways — pucks stolen from the opponent.",
  "GV": "Giveaways — pucks turned over.",
  "SHFT": "Shifts.",
  "TOI": "Total time on ice.",
  "ESTOI": "Even-strength time on ice.",
  "PPTOI": "Power-play time on ice.",
  "SHTOI": "Short-handed (penalty-kill) time on ice.",
  "FOW": "Faceoffs won.",
  "FOL": "Faceoffs lost.",
  "FO%": "Faceoff win %.",
  // goalie
  "SV%": "Save percentage — saves / shots against.",
  "Saves": "Shots saved.",
  "Shots": "Shots on goal.",
  "Shots against": "Shots on goal the goalie faced.",
  "Shots faced": "Shots on goal the goalie faced.",
  "SA": "Shots against (on goal).",
  "GA": "Goals against.",
  "GSAx": "Goals saved above expected — goals prevented vs. the quality of shots faced. The best single goalie value stat.",
  "xG faced": "Expected goals faced — the quality of shots the goalie saw.",
  "xG/60 faced": "Expected goals faced per 60 minutes — shot-quality workload.",
  "SV% vs exp": "Save % above expected — actual save % minus what an average goalie posts on those shots.",
  "xG saved": "% of expected goals saved above average — GSAx as a share of the chance quality faced.",
  "Unblocked SV%": "Fenwick save % — save rate on unblocked shots (on goal + missed).",
  "HD SV%": "High-danger save % — save rate on slot / home-plate chances.",
  "Rebound ctrl": "Rebound control — share of saves frozen or steered to safety (no second chance). CV-tracked.",
};
